### ISSUE TITLE
Zig fetch this dependency

### ISSUE THREAD

**Issue by Gota7** [Gota7/zig-clay#12]
Should be able to use a simple zig fetch rather than copy the example.

**Comment by kruzr-app** [comment]
do a zig fetch --save git+https://github.com/Gota7/zig-clay in your project directory
Add this 
    const clay_dep = b.dependency("clay", .{
        .target = target,
        .optimize = optimize,
    });

    const clay = clay_dep.module("clay");
before 

    const exe = b.addExecutable(.{
        .name = "zigtest",
        .root_source_file = b.path("src/main.zig"),
        .target = target,
        .optimize = optimize,
    });
    
    then just add this after the exe is initialized
        exe.root_module.addImport("clay", clay);

**Comment by Gota7** [comment]
Closed by #13

**Comment by Gota7** [comment]
> do a zig fetch --save git+https://github.com/Gota7/zig-clay in your project directory Add this const clay_dep = b.dependency("clay", .{ .target = target, .optimize = optimize, });
> 
> ```
> const clay = clay_dep.module("clay");
> ```
> 
> before
> 
> ```
> const exe = b.addExecutable(.{
>     .name = "zigtest",
>     .root_source_file = b.path("src/main.zig"),
>     .target = target,
>     .optimize = optimize,
> });
> 
> then just add this after the exe is initialized
>     exe.root_module.addImport("clay", clay);
> ```

Thank you for the suggestion! Applied now.
